package schach.controller.interfaces;

import schach.controller.ai.SimpleAi;
import schach.model.Board;

/**
 * Interface for the different ai
 */
public class AiInteface {

    private SimpleAi ai;

    private boolean white;

    /**
     * Constructor to initialize the fields
     * @param board the board the ai will be used on
     * @param isWhite true if ai is white, false if black
     */
    public AiInteface(Board board, boolean isWhite){
        this.white = isWhite;
        this.ai = new SimpleAi(board, white);
    }

    /**
     * Getter for the next move generated by the ai
     * @return String representing the move, like "a2-a4"
     */
    protected String getNextMove(){
        return ai.getNextMove();
    }
}
